### ISSUE TITLE
Mapbox tile urls broken

### ISSUE THREAD

**Issue by harry-wood** [pokelondon/pintsinthesun#17]
Oh no! It's sunny outside and pintsinthesun.co.uk is broken!

Looks like the mapbox tile URLs are no longer working. 

<img width="760" alt="Screenshot 2021-07-21 at 15 42 16" src="https://user-images.githubusercontent.com/227525/126508827-42be8aad-c566-480d-bb30-6225920ba4ad.png">

e.g.  http://a.tiles.mapbox.com/v3/poke.ifimp0gk/18/131016/87149.png

I don't know if that's because it's an old base URL which used to work and mapbox switched it off, or if that's an API key you stopped paying for and mapbox switched it off.

**Comment by 2xAA** [comment]
Fixed in #18.
